[package]
name = "vfio-user-proto"
version = "0.1.2"
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
license = "Apache-2.0"
description = "Support for vfio-user devices"
repository = "https://github.com/rust-vmm/vfio-user"

[dependencies]
zerocopy.workspace = true
strum = { version = "0.27.2", features = ["derive"] }
bitflags.workspace = true
serde.workspace = true
vfio-bindings.workspace = true
